/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package com.mycompany.twilio.servlet;

import java.io.*;
import java.sql.*;
import jakarta.servlet.*;
import jakarta.servlet.http.*;
import java.util.Random;
import jakarta.servlet.ServletContext;
// Twilio SDK Imports
import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;
import jakarta.servlet.annotation.WebServlet;

/**
 *
 * @author omar
 */
@WebServlet("/VerifyServlet")
public class VerifyServlet extends HttpServlet {

    public void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html;charset=UTF-8");
        PrintWriter writer = response.getWriter();
        
        HttpSession session = request.getSession(false);
        
        // Check if session exists
        if (session == null) {
            writer.println("<style>.error-msg { color: red; background: #ffe6e6; padding: 10px; border:1px solid red; }</style>");
            writer.println("<div class=\"error-msg\" >");
            writer.println("Session expired. Please <a href=\"Registration.html\">register again</a>.");
            writer.println("</div>");
            return;
        }
        
        if ("yes".equals(session.getAttribute("isLoggedIn"))) {
            response.sendRedirect("home.jsp");
            return;
        }

        // OTP generated by OTP generation 
        String OTP = (String) session.getAttribute("OTP");
        
        // Check if OTP exists in session
        if (OTP == null) {
            writer.println("<style>.error-msg { color: red; background: #ffe6e6; padding: 10px; border:1px solid red; }</style>");
            writer.println("<div class=\"error-msg\" >");
            writer.println("OTP session data not found. Please <a href=\"Registration.html\">register again</a>.");
            writer.println("</div>");
            return;
        }

        // OTP input by client
        String EnteredOTP = request.getParameter("otp");
        try {

            if (!OTP.equals(EnteredOTP)) {
                writer.println("<style>.error-msg { color: red; background: #ffe6e6; padding: 10px; border:1px solid red; }</style>");
                writer.println("<div class=\"error-msg\" >");
                writer.println("Invalid verification code! Please try again.");
                writer.println("<form action=\"VerifyServlet\" method=\"post\">"
                        + "    <input type=\"text\" name=\"otp\" placeholder=\"Enter OTP\" required>"
                        + "    <button type=\"submit\">Verify</button>\n"
                        + "</form>");
                writer.println("</div>");

            } else {

                ServletContext ctx = getServletContext();
                Connection con = (Connection) ctx.getAttribute("DBConnection");
                PreparedStatement ps = con.prepareStatement(
                          "UPDATE users "
                        + "SET is_verified = true "
                        + "WHERE msisdn=? ");

                String msisdn = (String) session.getAttribute("msisdn");
                ps.setString(1, msisdn);

                int updatedRows = ps.executeUpdate();
                if (updatedRows == 0) {
                    response.sendRedirect("Verify.html?error=1");
                } else {
                    PreparedStatement ps2 = con.prepareStatement("SELECT user_id, is_admin FROM users WHERE msisdn = ?");
                    ps2.setString(1, msisdn);
                    ResultSet rs = ps2.executeQuery();
                    if (rs.next()) {
                        session.setAttribute("userId", rs.getInt("user_id"));
                        session.setAttribute("is_admin", String.valueOf(rs.getBoolean("is_admin")));
                    }
                    session.setAttribute("isLoggedIn", "yes");
                    response.sendRedirect("home.jsp");
                }
            }
        } catch (Exception e) {
            writer.println("<style>.error-msg { color: red; background: #ffe6e6; padding: 10px; border:1px solid red; }</style>");
            writer.println("<div class=\"error-msg\" >");
            writer.println("Error during verification: " + e.getMessage());
            writer.println("<br><a href=\"Registration.html\">Back to Registration</a>");
            writer.println("</div>");
            e.printStackTrace();
        }
    }
}
