/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package com.mycompany.twilio;

import java.io.*;
import java.sql.*;
import jakarta.servlet.*;
import jakarta.servlet.http.*;
import java.util.Random;
import jakarta.servlet.ServletContext;
// Twilio SDK Imports
import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;

/**
 *
 * @author omar
 */
public class VerifyServlet extends HttpServlet {

    public void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession(false);
        if (session != null && "yes".equals(session.getAttribute("isLoggedIn"))) {
            response.sendRedirect("Profile.html");
            return;
        }

        PrintWriter writer = response.getWriter();
        // OTP generated by OTP generation 
        String OTP = (String) session.getAttribute("OTP");

        // OTP input by client
        String EnteredOTP = request.getParameter("otp");
        try {

            if (!OTP.equals(EnteredOTP)) {
                writer.println("<style>.error-msg { color: red; background: #ffe6e6; padding: 10px; border:1px solid red; }</style>");
                writer.println("<div class=\"error-msg\" >");
                writer.println("Invalid verification code! Please try again.");
                writer.println("<form action=\"Verify.html\" method=\"post\">"
                        + "    <button type=\"submit\">Retry</button>\n"
                        + "</form>");
                writer.println("</div>");

            } else {

                ServletContext ctx = getServletContext();
                Connection con = (Connection) ctx.getAttribute("DBConnection");
                PreparedStatement ps = con.prepareStatement("UPDATE users"
                        + " SET is_verified = true"
                        + " WHERE msisdn=?");

                String msisdn = (String) session.getAttribute("msisdn");
                ps.setString(1, msisdn);

                int rs = ps.executeUpdate();
                if (rs == 0) {
                    //response.sendRedirect("Registration.html");
                    response.sendRedirect("Verify.html?error=1");
                } else {
                    session.setAttribute("isLoggedIn", "yes");
                    response.sendRedirect("Profile.html");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
